#!/usr/bin/env python2

import os
from sys import argv, exit
import threading
import subprocess

import pymol
from pymol import cmd, stored
pymol.pymol_argv = ['pymol', '-qc']
pymol.finish_launching()


def calc_sasa(prog, resiList, thread_id, results):
	results[thread_id] = subprocess.check_output([prog, ','.join(resiList)]).replace(' ', '\t')

def calc_sasa_parallel(prog, resiList, num_threads):
	threads = []
	results = [""] * num_threads
	q = len(resiList) / num_threads
	r = len(resiList) % num_threads

	lb = ub = 0
	for i in xrange(num_threads):
		ub = lb + q + (1 if i < r else 0)
		threads.append(threading.Thread(target = calc_sasa, args = (prog, resiList[lb:ub], i, results)))
		threads[-1].start()
		lb = ub

	for thread in threads:
		thread.join()

	return "".join(results)


if len(argv) != 3:
	print("Usage: calc_sasa_rRNA_pymol script_path num_threads")
	exit(-1)

prog = os.path.expanduser(argv[1]) + "/calc_sasa_pymol"
num_threads = int(argv[2])

# Load pdbs
cmd.load("3ofa.pdb")
cmd.load("3ofc.pdb")
cmd.alter("/3ofc//A", "chain='SA'")

# Create ribosome complex
cmd.create("mycomp", "3ofa 3ofc")


with open("ecoli_16S.sasa", "w") as fout:
	# Obtain resi
	stored.residues = []
	cmd.iterate("mycomp//A//O2'", "stored.residues.append(resi)")
	fout.write(calc_sasa_parallel(prog, stored.residues, num_threads))
