#!/usr/bin/env python

from sys import argv, exit

if len(argv) != 3:
    print("Usage: convert input.fas output.fa")
    exit(-1)

mymap = {'1':"Chr1", '2':"Chr2", '3':"Chr3", '4':"Chr4", '5':"Chr5", 'm':"ChrM", 'c':"ChrC"}

fin = open(argv[1])
fout = open(argv[2], "w")

for line in fin:
    if line.startswith('>'):
        line = ">" + mymap[line[1]] + "\n"
    fout.write(line)

fin.close()
fout.close()
