#!/usr/bin/env Rscript

argv = commandArgs(TRUE)
if (length(argv) != 3) {
   cat("Usage: generate_input_list input.expr mappability_file output_file\n")
   q(status = 1)
}

data = read.table(argv[1], header=T, stringsAsFactors = FALSE)
mapp = read.table(argv[2], header=F)
idx = data[,"TPM"] >= 50 & data[,"length"] >= 100 & mapp[,2] > 0.0
write.table(data[idx, "transcript_id"], file = argv[3], quote = FALSE, row.names = FALSE, col.names = FALSE)
