#!/usr/bin/env python

from sys import argv, exit

try:
    xrange
except NameError:
    xrange = range


if len(argv) != 3:
    print("Usage: python readModelSE2PE input.read_model output.read_model")
    exit(-1)

fin = open(argv[1])
fout = open(argv[2], "w")

line = fin.readline()
fout.write(line)

fin.readline()
fout.write("3\n")

chunk = chunk2 = ""
for i in xrange(5):
    line = fin.readline()
    chunk += line
    chunk2 += line
    if i == 1:
        chunk2 = list(chunk2)
        chunk2[-2] = '2'
        chunk2 = "".join(chunk2)
    
fout.write(chunk)
fout.write(chunk2)

while True:
    line = fin.readline()
    if line == "":
        break
    fout.write(line)

fin.close()
fout.close()

