#!/usr/bin/env python

from sys import argv, exit

if len(argv) != 3:
    print("Usage: convert_to_rsem_model input_PROBer_read_model output_rsem_model")
    exit(-1)

with open(argv[1]) as fin:
    with open(argv[2], "w") as fout:
        for i in range(5):
            next(fin)
        fout.write("1\n\n1.0\n\n")
        
        next(fin)
        fout.write("36\t37\t1\n")
        fout.write(next(fin))
        
        for i in range(2):
            next(fin)
        fout.write("\n0\n\n0\n\n")
        
        s = int(next(fin)[:-1])
        fout.write(str(s) + "\n")
        fout.write(next(fin))
        for i in range(s):
            fout.write(next(fin))
        fout.write("\n")

        for i in range(12):
            next(fin)
        [s, c] = [int(x) for x in next(fin)[:-1].split('\t')]
        fout.write("{}\t{}\n".format(s, c))
        for i in range(s):
            for j in range(c):
                fout.write(next(fin))
            fout.write(next(fin))

        next(fin)
        next(fin)
        fout.write("{}\t{}\n".format(s, c))
        line = next(fin)
        for i in range(s):
            fout.write(line)