#!/usr/bin/env python

from sys import argv, exit

if len(argv) <= 3:
    print("Usage: gen_pseudoU_truth output_file length 0-based-pos ...")
    exit(-1)

truth = [0] * int(argv[2])
for pos in argv[3:]:
    truth[int(pos)] = 1

with open(argv[1], "w") as fout:
    fout.write(" ".join([str(x) for x in truth]) + "\n")
