#!/usr/bin/env python

from sys import argv, exit

if len(argv) != 3:
	print("Usage: gen_mouse_remove_list input.gtf remove_list.txt")
	exit(-1)

start_string = "transcript_id \""
end_string = "\";"
chosen_5S = "ENSMUST00000178106" # n-R5s100, which overlaps RefSeq NR_046118

remove_list = set()
with open(argv[1]) as fin:
	for line in fin:
		fields = line.strip().split('\t')
		if fields[1] == "rRNA":
			pos = fields[8].find(start_string) + len(start_string)
			epos = fields[8].find(end_string, pos)
			tid = fields[8][pos:epos]
			if tid != chosen_5S:
				remove_list.add(tid)

with open(argv[2], "w") as fout:
	fout.write("ENSMUST00000082388\n")
	fout.write("\n".join(list(remove_list)) + "\n")
