#!/usr/bin/env python

from sys import argv, exit

if len(argv) != 4:
	print("Usage: integrate_umi_info_GrannemanLab info_file input_name output_name")
	exit(-1)

with open(argv[1]) as finfo, open(argv[2] + "_1.fastq") as fin1, open(argv[2] + "_2.fastq") as fin2, \
	open(argv[3] + "_1.fastq", "w") as fout1, open(argv[3] + "_2.fastq", "w") as fout2:
	for umi in finfo:
		umi = umi.strip()

		tag1 = next(fin1).strip().split()[0]
		seq1 = next(fin1)
		tmp = next(fin1)
		qual1 = next(fin1)

		tag2 = next(fin2).strip().split()[0]
		seq2 = next(fin2)
		tmp = next(fin2)
		qual2 = next(fin2)

		fout1.write("@{0}:{1}\n{2}+\n{3}".format(umi, tag1[1:], seq1[1:], qual1[1:]))
		fout2.write("@{0}:{1}\n{2}+\n{3}".format(umi, tag2[1:], seq2, qual2))

