#!/usr/bin/env Rscript

argv = commandArgs(TRUE)
if (length(argv) != 5) {
	 cat("Usage: plot_PR_ROC_sasa ground_truth_dir row_list(',') exclude_bp experiment_prefix output_name\n")
	 q(status = 1)
}

library(PRROC)

collectTruth = function(name, ground_truth_dir, exclude_bp) {
	truth = scan(sprintf("%s/yeast_%s.structure", ground_truth_dir, name), what = 0)
	isAC = scan(sprintf("%s/yeast_%s.isac", ground_truth_dir, name), what = 0)
	
	# load sasa
	data = read.table(sprintf("%s/yeast_%s.sasa", ground_truth_dir, name))
	sasa = rep(-1.0, length(truth))
	sasa[data[,1]] = data[,3]

	# true positives and negatives
	tp = isAC & truth == 1 & sasa > 2.0
	tn = isAC & truth == 0
	idx = tp | tn

	# select positions used for plotting
	pos = which(idx[1:(length(truth) - exclude_bp)])

	return(list(truth = truth, pos = pos))
}

collectPROBer = function(pos, file_name) {
	prober = scan(file_name, what = "", skip = pos, nlines = 1)
	as.numeric(prober[3:length(prober)])
}

collectScore = function(pos, file_name) {
	scan(file_name, what = 0.0, skip = pos - 1, nlines = 1)
}

calculateROC = function(id, estList, truthList) {
	pos = truthList[[id]]$pos
	truth = truthList[[id]]$truth
	roc.curve(estList[[id]][pos], weights.class0 = truth[pos], curve = T)
}

calculatePR = function(id, estList, truthList) {
	pos = truthList[[id]]$pos
	truth = truthList[[id]]$truth
	pr.curve(estList[[id]][pos], weights.class0 = truth[pos], curve = T)
}

plotROC = function(id, output_name, rRNAs, PROBerRocs, StructureFoldRocs, ModseekerRocs, icSHAPERocs) {
	pdf(sprintf("%s_roc_%s.pdf", output_name, rRNAs[id]))

	par(oma = c(0, 0, 0, 0), mar = c(5, 4, 0, 0) + 0.1)
	plot(PROBerRocs[[id]], lwd = 1, col = "red", auc.main = F, main = "") #rRNAs[id])
	if (!is.null(StructureFoldRocs)) plot(StructureFoldRocs[[id]], lwd = 1, col = "blue", add = T)
	plot(ModseekerRocs[[id]], lwd = 1, col = "green", add = T)
	plot(icSHAPERocs[[id]], lwd = 1, col = "orange", add = T)


	legends = c(as.expression(bquote(paste("PROBer, AUC = ", .(sprintf("%.2f", PROBerRocs[[id]]$auc))))))
	if (!is.null(StructureFoldRocs)) {
		legends = c(legends, as.expression(bquote(paste("StructureFold, AUC = ", .(sprintf("%.2f", StructureFoldRocs[[id]]$auc))))))
	}
	legends = c(legends, as.expression(bquote(paste("Mod-seeker, AUC = ", .(sprintf("%.2f", ModseekerRocs[[id]]$auc))))),
							as.expression(bquote(paste("icSHAPE, AUC = ", .(sprintf("%.2f", icSHAPERocs[[id]]$auc))))))

	colors = "red"
	if (!is.null(StructureFoldRocs)) colors = c(colors, "blue")
	colors = c(colors, "green", "orange")

	legend("bottomright", legend = legends, lty = 1, col = colors)

	null = dev.off()

	return(NULL)
}

plotPR = function(id, output_name, rRNAs, PROBerPrs, StructureFoldPrs, ModseekerPrs, icSHAPEPrs) {
	pdf(sprintf("%s_pr_%s.pdf", output_name, rRNAs[id]))

	par(oma = c(0, 0, 0, 0), mar = c(5, 4, 0, 0) + 0.1)
	plot(PROBerPrs[[id]], lwd = 1, col = "red", auc.main = F, main = "") #rRNAs[id])
	if (!is.null(StructureFoldPrs)) plot(StructureFoldPrs[[id]], lwd = 1, col = "blue", add = T)
	plot(ModseekerPrs[[id]], lwd = 1, col = "green", add = T)
	plot(icSHAPEPrs[[id]], lwd = 1, col = "orange", add = T)


	legends = c(as.expression(bquote(paste("PROBer, AUC = ", .(sprintf("%.2f", PROBerPrs[[id]]$auc.integral))))))
	if (!is.null(StructureFoldPrs)) {
		legends = c(legends, as.expression(bquote(paste("StructureFold, AUC = ", .(sprintf("%.2f", StructureFoldPrs[[id]]$auc.integral))))))
	}
	legends = c(legends, as.expression(bquote(paste("Mod-seeker, AUC = ", .(sprintf("%.2f", ModseekerPrs[[id]]$auc.integral))))),
							as.expression(bquote(paste("icSHAPE, AUC = ", .(sprintf("%.2f", icSHAPEPrs[[id]]$auc.integral))))))

	colors = "red"
	if (!is.null(StructureFoldPrs)) colors = c(colors, "blue")
	colors = c(colors, "green", "orange")

	legend("topright", legend = legends, lty = 1, col = colors)

	null = dev.off()

	return(NULL)
}

fileList = c(sprintf("%s_PROBer.beta", argv[4]), sprintf("%s_%s.scores", argv[4], c("StructureFold", "Modseeker", "icSHAPE")))

rRNAs = c("18S", "25S")
rowList = as.numeric(unlist(strsplit(argv[2], split = ",")))

truthList = lapply(rRNAs, collectTruth, argv[1], as.numeric(argv[3]))

PROBerList = lapply(rowList, collectPROBer, fileList[1])
StructureFoldList = NULL
if (file.exists(fileList[2])) StructureFoldList = lapply(rowList, collectScore, fileList[2])
ModseekerList = lapply(rowList, collectScore, fileList[3])
icSHAPEList = lapply(rowList, collectScore, fileList[4])

PROBerRocs = lapply(1:2, calculateROC, PROBerList, truthList)
StructureFoldRocs = NULL
if (!is.null(StructureFoldList)) StructureFoldRocs = lapply(1:2, calculateROC, StructureFoldList, truthList)
ModseekerRocs = lapply(1:2, calculateROC, ModseekerList, truthList)
icSHAPERocs = lapply(1:2, calculateROC, icSHAPEList, truthList)


PROBerPrs = lapply(1:2, calculatePR, PROBerList, truthList)
StructureFoldPrs = NULL
if (!is.null(StructureFoldList)) StructureFoldPrs = lapply(1:2, calculatePR, StructureFoldList, truthList)
ModseekerPrs = lapply(1:2, calculatePR, ModseekerList, truthList)
icSHAPEPrs = lapply(1:2, calculatePR, icSHAPEList, truthList)

cat("ROCs\n")
null_vec = lapply(1:2, plotROC, argv[5], rRNAs, PROBerRocs, StructureFoldRocs, ModseekerRocs, icSHAPERocs)
cat("PRs\n")
null_vec = lapply(1:2, plotPR, argv[5], rRNAs, PROBerPrs, StructureFoldPrs, ModseekerPrs, icSHAPEPrs)
